version: '3.3'
volumes:
  pg_data:
  frontend:
  static:
  media:

services:
  db:
    image: postgres:16
    env_file: .env
    hostname: foodgram_pg
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    build: ../backend/
    depends_on:
      - db
    env_file: .env
    volumes:
      - static:/backend/collected_static/
      - media:/backend/media/
    environment:
      WAIT_HOSTS: foodgram_pg:5432
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - frontend:/app/result_build/build/
  nginx:
    build: ./
    depends_on:
      - frontend
      - backend
    ports:
      - "8000:80"
    volumes:
      - frontend:/var/www/frontend/
      - static:/var/html/static/
      - media:/var/html/media/
      - ./docs/:/var/html/api/docs/
